LIB_PATHS =  \
-LC:\Programming\vlc-1.1.11\sdk\lib \

LIBS = \
-lopengl32 \
-lvlc \

INCDIRS = \
-IC:/Programming/vlc-1.1.11/sdk/include \

TARGET = test

PACKAGE_DEPENDENCIES += mingw
include $(PROJECT_ROOT_DIR)/templates/GNUMakefile