LIB_PATHS =  \
-LC:\Programming\OpenAL\libs\Win64 \

LIBS = \
"C:\Programming\OpenAL\libs\Win32\OpenAL32.lib" \

INCDIRS = \
-IC:\Programming\OpenAL\include \

TARGET = test

PACKAGE_DEPENDENCIES += redirect
include $(PROJECT_ROOT_DIR)/templates/GNUMakefile